// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	exampleFieldNames          = builder.RawFieldNames(&Example{})
	exampleRows                = strings.Join(exampleFieldNames, ",")
	exampleRowsExpectAutoSet   = strings.Join(stringx.Remove(exampleFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	exampleRowsWithPlaceHolder = strings.Join(stringx.Remove(exampleFieldNames, "`shorten`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheExampleShortenPrefix = "cache:example:shorten:"
)

type (
	exampleModel interface {
		Insert(ctx context.Context, data *Example) (sql.Result, error)
		FindOne(ctx context.Context, shorten string) (*Example, error)
		Update(ctx context.Context, data *Example) error
		Delete(ctx context.Context, shorten string) error
	}

	defaultExampleModel struct {
		sqlc.CachedConn
		table string
	}

	Example struct {
		Shorten string `db:"shorten"` // shorten key
		Url     string `db:"url"`     // original url
	}
)

func newExampleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultExampleModel {
	return &defaultExampleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`example`",
	}
}

func (m *defaultExampleModel) Delete(ctx context.Context, shorten string) error {
	exampleShortenKey := fmt.Sprintf("%s%v", cacheExampleShortenPrefix, shorten)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `shorten` = ?", m.table)
		return conn.ExecCtx(ctx, query, shorten)
	}, exampleShortenKey)
	return err
}

func (m *defaultExampleModel) FindOne(ctx context.Context, shorten string) (*Example, error) {
	exampleShortenKey := fmt.Sprintf("%s%v", cacheExampleShortenPrefix, shorten)
	var resp Example
	err := m.QueryRowCtx(ctx, &resp, exampleShortenKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `shorten` = ? limit 1", exampleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, shorten)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExampleModel) Insert(ctx context.Context, data *Example) (sql.Result, error) {
	exampleShortenKey := fmt.Sprintf("%s%v", cacheExampleShortenPrefix, data.Shorten)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, exampleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Shorten, data.Url)
	}, exampleShortenKey)
	return ret, err
}

func (m *defaultExampleModel) Update(ctx context.Context, data *Example) error {
	exampleShortenKey := fmt.Sprintf("%s%v", cacheExampleShortenPrefix, data.Shorten)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `shorten` = ?", m.table, exampleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Url, data.Shorten)
	}, exampleShortenKey)
	return err
}

func (m *defaultExampleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheExampleShortenPrefix, primary)
}

func (m *defaultExampleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `shorten` = ? limit 1", exampleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultExampleModel) tableName() string {
	return m.table
}
