// Code generated by MockGen. DO NOT EDIT.
// Source: iot-zero/rpc-transform/model (interfaces: ExampleModel)

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExampleModel is a mock of ExampleModel interface.
type MockExampleModel struct {
	ctrl     *gomock.Controller
	recorder *MockExampleModelMockRecorder
}

// MockExampleModelMockRecorder is the mock recorder for MockExampleModel.
type MockExampleModelMockRecorder struct {
	mock *MockExampleModel
}

// NewMockExampleModel creates a new mock instance.
func NewMockExampleModel(ctrl *gomock.Controller) *MockExampleModel {
	mock := &MockExampleModel{ctrl: ctrl}
	mock.recorder = &MockExampleModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExampleModel) EXPECT() *MockExampleModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockExampleModel) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExampleModelMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExampleModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockExampleModel) FindOne(arg0 context.Context, arg1 string) (*Example, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*Example)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockExampleModelMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockExampleModel)(nil).FindOne), arg0, arg1)
}

// Insert mocks base method.
func (m *MockExampleModel) Insert(arg0 context.Context, arg1 *Example) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockExampleModelMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockExampleModel)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockExampleModel) Update(arg0 context.Context, arg1 *Example) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExampleModelMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExampleModel)(nil).Update), arg0, arg1)
}
