// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	menuFieldNames          = builder.RawFieldNames(&Menu{})
	menuRows                = strings.Join(menuFieldNames, ",")
	menuRowsExpectAutoSet   = strings.Join(stringx.Remove(menuFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	menuRowsWithPlaceHolder = strings.Join(stringx.Remove(menuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	menuModel interface {
		Insert(ctx context.Context, data *Menu) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Menu, error)
		Update(ctx context.Context, data *Menu) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Menu struct {
		Id       uint64 `db:"id"`
		ParentId uint64 `db:"parent_id"`
		MenuKey  string `db:"menu_key"`
		Title    string `db:"title"`
		HasChild string `db:"has_child"`
	}
)

func newMenuModel(conn sqlx.SqlConn) *defaultMenuModel {
	return &defaultMenuModel{
		conn:  conn,
		table: "`menu`",
	}
}

func (m *defaultMenuModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMenuModel) FindOne(ctx context.Context, id uint64) (*Menu, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", menuRows, m.table)
	var resp Menu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenuModel) Insert(ctx context.Context, data *Menu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, menuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ParentId, data.MenuKey, data.Title, data.HasChild)
	return ret, err
}

func (m *defaultMenuModel) Update(ctx context.Context, data *Menu) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, menuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ParentId, data.MenuKey, data.Title, data.HasChild, data.Id)
	return err
}

func (m *defaultMenuModel) tableName() string {
	return m.table
}
