// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleMenuFieldNames          = builder.RawFieldNames(&RoleMenu{})
	roleMenuRows                = strings.Join(roleMenuFieldNames, ",")
	roleMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(roleMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	roleMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(roleMenuFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	roleMenuModel interface {
		Insert(ctx context.Context, data *RoleMenu) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*RoleMenu, error)
		FindOneByRoleIdMenuId(ctx context.Context, roleId uint64, menuId uint64) (*RoleMenu, error)
		Update(ctx context.Context, data *RoleMenu) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultRoleMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RoleMenu struct {
		Id     uint64 `db:"id"`
		RoleId uint64 `db:"role_id"`
		MenuId uint64 `db:"menu_id"`
	}
)

func newRoleMenuModel(conn sqlx.SqlConn) *defaultRoleMenuModel {
	return &defaultRoleMenuModel{
		conn:  conn,
		table: "`role_menu`",
	}
}

func (m *defaultRoleMenuModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoleMenuModel) FindOne(ctx context.Context, id uint64) (*RoleMenu, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", roleMenuRows, m.table)
	var resp RoleMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleMenuModel) FindOneByRoleIdMenuId(ctx context.Context, roleId uint64, menuId uint64) (*RoleMenu, error) {
	var resp RoleMenu
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and `menu_id` = ? limit 1", roleMenuRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, menuId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleMenuModel) Insert(ctx context.Context, data *RoleMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, roleMenuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.MenuId)
	return ret, err
}

func (m *defaultRoleMenuModel) Update(ctx context.Context, newData *RoleMenu) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roleMenuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.RoleId, newData.MenuId, newData.Id)
	return err
}

func (m *defaultRoleMenuModel) tableName() string {
	return m.table
}
