// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateProductReq struct {
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
}

type CreateProductResp struct {
	Id uint64 `json:"id"`
}

type CreateRoleReq struct {
	TenantId uint64 `json:"tenantId"`
	RoleName string `json:"roleName"`
	Enable   bool   `json:"enable,optional,default=true"`
}

type CreateRoleResp struct {
	Id uint64 `json:"id"`
}

type CreateTenantReq struct {
	TenantName string `json:"tenantName"`
	Email      string `json:"email,optional"`
}

type CreateTenantResp struct {
	Id uint64 `json:"id"`
}

type CreateUserReq struct {
	TenantId uint64 `json:"tenantId"`
	Username string `json:"username"`
	Password string `json:"password"`
	RoleId   uint64 `json:"roleId"`
	Enable   bool   `json:"enable,optional,default=true"`
}

type CreateUserResp struct {
	Id uint64 `json:"id"`
}

type ExpandReq struct {
	Shorten string `form:"shorten"`
}

type ExpandResp struct {
	Url string `json:"url"`
}

type GetMenuTreeResp struct {
	List []MenuInfo `json:"list"`
}

type ListProductReq struct {
	PageIndex   int64  `form:"pageIndex,default=1"`
	PageSize    int64  `form:"pageSize,default=20"`
	ProductName string `form:"productName,optional"`
}

type ListProductResp struct {
	Total int64         `json:"total"`
	List  []ProductInfo `json:"list"`
}

type ListRoleReq struct {
	PageIndex int64  `form:"pageIndex,default=1"`
	PageSize  int64  `form:"pageSize,default=20"`
	TenantId  uint64 `form:"tenantId,optional"`
	RoleName  string `form:"roleName,optional"`
}

type ListRoleResp struct {
	Total int64      `json:"total"`
	List  []RoleInfo `json:"list"`
}

type ListTenantReq struct {
	PageIndex  int64  `form:"pageIndex,default=1"`
	PageSize   int64  `form:"pageSize,default=20"`
	TenantName string `form:"tenantName,optional"`
}

type ListTenantResp struct {
	Total int64        `json:"total"`
	List  []TenantInfo `json:"list"`
}

type ListUserReq struct {
	PageIndex int64  `form:"pageIndex,default=1"`
	PageSize  int64  `form:"pageSize,default=20"`
	TenantId  uint64 `form:"tenantId,optional"`
	Username  string `form:"username,optional"`
}

type ListUserResp struct {
	Total int64      `json:"total"`
	List  []UserInfo `json:"list"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Username string `json:"username"`
	Token    string `json:"token"`
}

type MenuInfo struct {
	Id       uint64     `json:"id"`
	MenuKey  string     `json:"menuKey"`
	Title    string     `json:"title"`
	ParentId uint64     `json:"parentId"`
	HasChild string     `json:"hasChild"`
	Children []MenuInfo `json:"children,optional,omitempty"`
}

type ProductIdPathReq struct {
	Id uint64 `path:"id"`
}

type ProductInfo struct {
	Id          uint64 `json:"id"`
	ProductCode string `json:"productCode"`
	ProductName string `json:"productName"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

type RoleIdPathReq struct {
	Id uint64 `path:"id"`
}

type RoleInfo struct {
	Id        uint64 `json:"id"`
	RoleType  string `json:"roleType"`
	RoleName  string `json:"roleName"`
	Enable    bool   `json:"enable"`
	TenantId  uint64 `json:"tenantId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type ShortenReq struct {
	Url string `form:"url"`
}

type ShortenResp struct {
	Shorten string `json:"shorten"`
}

type TenantIdPathReq struct {
	Id uint64 `path:"id"`
}

type TenantInfo struct {
	Id         uint64 `json:"id"`
	TenantName string `json:"tenantName"`
	Email      string `json:"email"`
	CreatedAt  string `json:"createdAt"`
	UpdatedAt  string `json:"updatedAt"`
}

type UpdateProductReq struct {
	Id          uint64 `path:"id"`
	ProductCode string `json:"productCode,optional"`
	ProductName string `json:"productName,optional"`
}

type UpdateRoleReq struct {
	Id       uint64 `path:"id"`
	RoleName string `json:"roleName,optional"`
	Enable   *bool  `json:"enable,optional"`
}

type UpdateTenantReq struct {
	Id         uint64 `path:"id"`
	TenantName string `json:"tenantName,optional"`
	Email      string `json:"email,optional"`
}

type UpdateUserPasswordReq struct {
	Username string `path:"username"`
	Password string `json:"password"`
}

type UpdateUserReq struct {
	Username string `path:"username"`
	RoleId   uint64 `json:"roleId,optional"`
	Enable   *bool  `json:"enable,optional"`
}

type UserInfo struct {
	Id        uint64 `json:"id"`
	Username  string `json:"username"`
	Enable    bool   `json:"enable"`
	RoleId    uint64 `json:"roleId"`
	TenantId  uint64 `json:"tenantId"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserUsernamePathReq struct {
	Username string `path:"username"`
}
