// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthAclRule struct {
	Permission string `json:"permission"`
	Action     string `json:"action"`
	Topic      string `json:"topic"`
	Qos        []int  `json:"qos,omitempty"`
}

type AuthReq struct {
	Clientid string `form:"clientid"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthResp struct {
	Result      string            `json:"result"`
	IsSuperuser bool              `json:"is_superuser"`
	ClientAttrs map[string]string `json:"client_attrs,omitempty"`
	ExpireAt    *int64            `json:"expire_at,omitempty"`
	Acl         []AuthAclRule     `json:"acl,omitempty"`
}
