// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tenantsFieldNames          = builder.RawFieldNames(&Tenants{})
	tenantsRows                = strings.Join(tenantsFieldNames, ",")
	tenantsRowsExpectAutoSet   = strings.Join(stringx.Remove(tenantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	tenantsRowsWithPlaceHolder = strings.Join(stringx.Remove(tenantsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	tenantsModel interface {
		Insert(ctx context.Context, data *Tenants) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Tenants, error)
		FindOneByTenantName(ctx context.Context, tenantName string) (*Tenants, error)
		Update(ctx context.Context, data *Tenants) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTenantsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Tenants struct {
		Id         uint64         `db:"id"`
		CreatedAt  sql.NullTime   `db:"created_at"`
		UpdatedAt  sql.NullTime   `db:"updated_at"`
		DeletedAt  sql.NullTime   `db:"deleted_at"`
		TenantName string         `db:"tenant_name"`
		Email      sql.NullString `db:"email"`
	}
)

func newTenantsModel(conn sqlx.SqlConn) *defaultTenantsModel {
	return &defaultTenantsModel{
		conn:  conn,
		table: "`tenants`",
	}
}

func (m *defaultTenantsModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTenantsModel) FindOne(ctx context.Context, id uint64) (*Tenants, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tenantsRows, m.table)
	var resp Tenants
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantsModel) FindOneByTenantName(ctx context.Context, tenantName string) (*Tenants, error) {
	var resp Tenants
	query := fmt.Sprintf("select %s from %s where `tenant_name` = ? limit 1", tenantsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTenantsModel) Insert(ctx context.Context, data *Tenants) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, tenantsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeletedAt, data.TenantName, data.Email)
	return ret, err
}

func (m *defaultTenantsModel) Update(ctx context.Context, newData *Tenants) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, tenantsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.DeletedAt, newData.TenantName, newData.Email, newData.Id)
	return err
}

func (m *defaultTenantsModel) tableName() string {
	return m.table
}
