// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	tenant "iotplatform/services/api/internal/handler/tenant"
	"iotplatform/services/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/expand",
				Handler: ExpandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tenants",
				Handler: tenant.CreateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tenants",
				Handler: tenant.ListTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tenants/:id",
				Handler: tenant.GetTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tenants/:id",
				Handler: tenant.UpdateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tenants/:id",
				Handler: tenant.DeleteTenantHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
