// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	product "iotplatform/services/api/internal/handler/product"
	role "iotplatform/services/api/internal/handler/role"
	tenant "iotplatform/services/api/internal/handler/tenant"
	"iotplatform/services/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/expand",
				Handler: ExpandHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shorten",
				Handler: ShortenHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/products",
				Handler: product.CreateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products",
				Handler: product.ListProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/products/:id",
				Handler: product.GetProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/products/:id",
				Handler: product.UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/products/:id",
				Handler: product.DeleteProductHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/roles",
				Handler: role.CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles",
				Handler: role.ListRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/roles/:id",
				Handler: role.GetRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/roles/:id",
				Handler: role.UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/roles/:id",
				Handler: role.DeleteRoleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/tenants",
				Handler: tenant.CreateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tenants",
				Handler: tenant.ListTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tenants/:id",
				Handler: tenant.GetTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tenants/:id",
				Handler: tenant.UpdateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tenants/:id",
				Handler: tenant.DeleteTenantHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
