// Code generated by MockGen. DO NOT EDIT.
// Source: iotplatform/services/model (interfaces: PlatformModel)

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPlatformModel is a mock of PlatformModel interface.
type MockPlatformModel struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformModelMockRecorder
}

// MockPlatformModelMockRecorder is the mock recorder for MockPlatformModel.
type MockPlatformModelMockRecorder struct {
	mock *MockPlatformModel
}

// NewMockPlatformModel creates a new mock instance.
func NewMockPlatformModel(ctrl *gomock.Controller) *MockPlatformModel {
	mock := &MockPlatformModel{ctrl: ctrl}
	mock.recorder = &MockPlatformModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatformModel) EXPECT() *MockPlatformModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPlatformModel) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPlatformModelMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlatformModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockPlatformModel) FindOne(arg0 context.Context, arg1 string) (*Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockPlatformModelMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockPlatformModel)(nil).FindOne), arg0, arg1)
}

// Insert mocks base method.
func (m *MockPlatformModel) Insert(arg0 context.Context, arg1 *Platform) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockPlatformModelMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockPlatformModel)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockPlatformModel) Update(arg0 context.Context, arg1 *Platform) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPlatformModelMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPlatformModel)(nil).Update), arg0, arg1)
}
