// Code generated by MockGen. DO NOT EDIT.
// Source: iotplatform/services/model (interfaces: ShorturlModel)

// Package model is a generated GoMock package.
package model

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShorturlModel is a mock of ShorturlModel interface.
type MockShorturlModel struct {
	ctrl     *gomock.Controller
	recorder *MockShorturlModelMockRecorder
}

// MockShorturlModelMockRecorder is the mock recorder for MockShorturlModel.
type MockShorturlModelMockRecorder struct {
	mock *MockShorturlModel
}

// NewMockShorturlModel creates a new mock instance.
func NewMockShorturlModel(ctrl *gomock.Controller) *MockShorturlModel {
	mock := &MockShorturlModel{ctrl: ctrl}
	mock.recorder = &MockShorturlModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShorturlModel) EXPECT() *MockShorturlModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockShorturlModel) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShorturlModelMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShorturlModel)(nil).Delete), arg0, arg1)
}

// FindOne mocks base method.
func (m *MockShorturlModel) FindOne(arg0 context.Context, arg1 string) (*Shorturl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*Shorturl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockShorturlModelMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockShorturlModel)(nil).FindOne), arg0, arg1)
}

// Insert mocks base method.
func (m *MockShorturlModel) Insert(arg0 context.Context, arg1 *Shorturl) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockShorturlModelMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockShorturlModel)(nil).Insert), arg0, arg1)
}

// Update mocks base method.
func (m *MockShorturlModel) Update(arg0 context.Context, arg1 *Shorturl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShorturlModelMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShorturlModel)(nil).Update), arg0, arg1)
}
