// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platformFieldNames          = builder.RawFieldNames(&Platform{})
	platformRows                = strings.Join(platformFieldNames, ",")
	platformRowsExpectAutoSet   = strings.Join(stringx.Remove(platformFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	platformRowsWithPlaceHolder = strings.Join(stringx.Remove(platformFieldNames, "`shorten`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePlatformShortenPrefix = "cache:platform:shorten:"
)

type (
	platformModel interface {
		Insert(ctx context.Context, data *Platform) (sql.Result, error)
		FindOne(ctx context.Context, shorten string) (*Platform, error)
		Update(ctx context.Context, data *Platform) error
		Delete(ctx context.Context, shorten string) error
	}

	defaultPlatformModel struct {
		sqlc.CachedConn
		table string
	}

	Platform struct {
		Shorten string `db:"shorten"` // shorten key
		Url     string `db:"url"`     // original url
	}
)

func newPlatformModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPlatformModel {
	return &defaultPlatformModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`platform`",
	}
}

func (m *defaultPlatformModel) Delete(ctx context.Context, shorten string) error {
	platformShortenKey := fmt.Sprintf("%s%v", cachePlatformShortenPrefix, shorten)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `shorten` = ?", m.table)
		return conn.ExecCtx(ctx, query, shorten)
	}, platformShortenKey)
	return err
}

func (m *defaultPlatformModel) FindOne(ctx context.Context, shorten string) (*Platform, error) {
	platformShortenKey := fmt.Sprintf("%s%v", cachePlatformShortenPrefix, shorten)
	var resp Platform
	err := m.QueryRowCtx(ctx, &resp, platformShortenKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `shorten` = ? limit 1", platformRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, shorten)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPlatformModel) Insert(ctx context.Context, data *Platform) (sql.Result, error) {
	platformShortenKey := fmt.Sprintf("%s%v", cachePlatformShortenPrefix, data.Shorten)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, platformRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Shorten, data.Url)
	}, platformShortenKey)
	return ret, err
}

func (m *defaultPlatformModel) Update(ctx context.Context, data *Platform) error {
	platformShortenKey := fmt.Sprintf("%s%v", cachePlatformShortenPrefix, data.Shorten)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `shorten` = ?", m.table, platformRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Url, data.Shorten)
	}, platformShortenKey)
	return err
}

func (m *defaultPlatformModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePlatformShortenPrefix, primary)
}

func (m *defaultPlatformModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `shorten` = ? limit 1", platformRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPlatformModel) tableName() string {
	return m.table
}
