Name: transform.rpc
DevServer:
  Enabled: false
Log:
  Mode: console
ListenOn: 0.0.0.0:9001
Etcd:
  Hosts:
  - etcd:2379
  Key: transform.rpc
DataSource: root:zzz888@tcp(mysql:3306)/myexampledb
Table: shorturl
Cache:
  - Host: redis:6379

