services:
  transform-rpc:
    build:
      context: ../../
      dockerfile: services/rpc-transform/Dockerfile
      target: debug
    image: debug-transform-rpc-image:latest
    container_name: debug-transform-rpc-container
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "9001:9001"
      - "2346:2345"

  platform-api:
    build:
      context: ../../
      dockerfile: services/api/Dockerfile
      target: debug
    image: debug-platform-api-image:latest
    container_name: debug-platform-api-container
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "8080:8080"
      - "2345:2345"
