// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthReq struct {
	Clientid string `form:"clientid"`
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthResp struct {
	Result string `json:"result"`
}
